### ISSUE TITLE
Rekognitionin vaihto Textractiin (mahdollisesti)

### ISSUE THREAD

**Issue by aa3689** [jamktiko/reseptipankki#221]
Devaajana haluan Rekognitionin sijaan todennäköisesti käyttää Textractia, koska siinä ei ole 100 sanan rajoitusta tekstin tunnistuksessa ja tunnistus toimii hieman paremmin.

- [ ] Rekognition on vaihdettu Textractiin

- [ ] Asiat toimivat vähintään yhtä hyvin kuin ennen vaihtoa

Definition of Done​

- [ ] Hyväksymiskriteerit täyttyvät.
- [ ] Hyväksymiskriteerit on testattu.
- [ ] Julkaisutiedot on kirjoitettu.

**Comment by CtrlAltToni** [comment]
Tätä yritin ottaa käyttöön, mutta ei ollut niin simppeliä mitä odotettiin. Viimeisimmästä (?) viikkoraportista löytyy kattavampi selonteo
