### ISSUE TITLE
MySQL-id:t randomeiksi merkkijonoiksi arvattavien numeroiden sijaan

### ISSUE THREAD

**Issue by AA2338** [jamktiko/reseptipankki#283]
Devaajana haluan, että resepteillä ja listoilla ei olisi tietokannassa ID:nä helposti arvattavaa lukua, koska ID:tä käytetään niiden URLeissa, ja kuka tahansa pääsee katsomaan vaikka yksityisiä reseptejä tai listoja kirjoittamalla urliin satunnaisia numeroita.

- [ ] Selvitä, saisiko MySQL:ssä jotenkin helposti ja tehokkaasti esimerkiksi satunnaisia merkkijonoja ID:n korvikkeiksi.

- [ ] Jos saa, toteuta niin meidän tietokantaamme.

- [ ] Frontendissä: Varmista, että reseptien ja listojen URL:it luodaan käyttäen näitä merkkijonoja ID:iden sijaan.

Definition of Done​

- [ ] Hyväksymiskriteerit täyttyvät.
- [ ] Koodi on kommentoitua.
- [ ] Hyväksymiskriteerit on testattu.
- [ ] Julkaisutiedot on kirjoitettu.

**Comment by IlmariM** [comment]
Tämä ei toimi ilman massiivista tietokannan uudelleen tekoa sekä backendin ja frontendin muuntamista
