### ISSUE TITLE
Reseptien lisääminen netistä

### ISSUE THREAD

**Issue by AA2338** [jamktiko/reseptipankki#4]
Käyttäjänä haluan lisätä netistä löytämäni reseptin sovellukseen pelkän linkin avulla, jottei reseptiä tarvitse alkaa kirjoittamaan tai kopioimaan sovellukseen.

- [x] Käyttäjä liittää kopioimansa linkin sovelluksen Lataa netistä -näkymän tekstikenttään ja painaa nappia.

- [x] Jos sovellus löytää linkin takaa reseptin, se avautuu reseptinlisäyslomakkeeseen.

- [x] Jos sovellus ei löydä linkin takaa reseptiä, se ilmoittaa tästä käyttäjälle.

Definition of Done​

- [x] Hyväksymiskriteerit täyttyvät.
- [x] Koodi on kommentoitua.
- [ ] Hyväksymiskriteerit on testattu.
- [x] Julkaisutiedot on kirjoitettu.

**Comment by AA2338** [comment]
**HUOM!** Toimii tällä hetkellä vain seuraavilla sivuilla: Kotikokki, Soppa365, Valio

**Comment by baritoni** [comment]
Testattu selaimilla:
Google Chrome: Versio: 107.0.5304.107 (Official Build) (64-bit)
Mozilla Firefox: Versio: 107.0.5304.107 (Official Build) (64-bit)
Microsoft Edge: Versio: 107.0.1418.56 (Official build) (64-bit)
