### ISSUE TITLE
Nginx käyttöön

### ISSUE THREAD

**Issue by AA2338** [jamktiko/reseptipankki#63]
Devaajana haluan, että projektissamme on Nginx käytössä, koska ???

- [ ] Ymmärrä mikä Nginx on ja miksi käytämme sitä
- [ ] Nginx on projektissamme käytössä ja se toimii

Definition of Done​

- [ ] Hyväksymiskriteerit täyttyvät.
- [ ] Hyväksymiskriteerit on testattu.
- [ ] Julkaisutiedot on kirjoitettu Githubiin.

**Comment by CtrlAltToni** [comment]
Nginx on oletuksena beanstalkissa käytössä, mutta vaatisi ilmeisesti configurointia jotta se oikeasti toimisi. Tämä jäi tekemättä
